function showInfo( figHandle, params, filename, path);
%
% (c) Sebastian Thees 17.2.2001, email: s_thees@yahoo.com
%
% Dept. of Neurologie, Charite, Berlin, Germany
%
if size(filename, 1) == 1
   imaHeaderInfo = char( ...
      path, ... 
      filename, ...
      ' ', ...
      [ 'probant:            ' params.name ], ...
      [ 'date/time:         ' params.date ' ' params.time ], ...
      [ 'sequence type: ' params.seqType], ...
      sprintf( 'scan duration:   %4.2f s', params.acquisitionTime), ...
      sprintf( 'rowVect:           %4.4f   %4.4f   %4.4f', params.rowVect(1), params.rowVect(2), params.rowVect(3)), ...
      sprintf( 'colVect:            %4.4f   %4.4f   %4.4f', params.colVect(1), params.colVect(2), params.colVect(3)), ...
      sprintf( 'normVect:         %4.4f   %4.4f   %4.4f', params.normVect(1), params.normVect(2), params.normVect(3)), ...
      sprintf( 'FoV:                 %4.2f  %4.2f', params.FoV(1), params.FoV(2)), ...
      sprintf( 'matrix:              %d  %d', params.matrix(1), params.matrix(2)), ...
      sprintf( 'sliceThickness: %d', params.sliceThickness), ...
      sprintf( 'distFactor:         %2.4f', params.distFactor), ...
      [ 'nSlices:             ' num2str( params.nSlices) ] );
else
   imaHeaderInfo = char( ...
      path, ... 
      ['first file: ' char( filename(1,:))  ], ...
      ['last file:  ' char(filename(end,:)) ], ...
      ' ', ...
      [ 'probant:            ' params.name ], ...
      [ 'date/time:         ' params.date ' ' params.time ], ...
      [ 'sequence type: ' params.seqType], ...
      sprintf( 'scan duration:   %4.2f s', params.acquisitionTime), ...
      sprintf( 'rowVect:           %4.4f   %4.4f   %4.4f', params.rowVect(1), params.rowVect(2), params.rowVect(3)), ...
      sprintf( 'colVect:            %4.4f   %4.4f   %4.4f', params.colVect(1), params.colVect(2), params.colVect(3)), ...
      sprintf( 'normVect:         %4.4f   %4.4f   %4.4f', params.normVect(1), params.normVect(2), params.normVect(3)), ...
      sprintf( 'FoV:                 %4.2f  %4.2f', params.FoV(1), params.FoV(2)), ...
      sprintf( 'matrix:              %d  %d', params.matrix(1), params.matrix(2)), ...
      sprintf( 'sliceThickness: %d', params.sliceThickness), ...
      sprintf( 'distFactor:         %2.4f', params.distFactor), ...
      [ 'nSlices:             ' num2str( params.nSlices) ] );
end
set( findobj( figHandle, 'Tag', 'imaHeaderInfo'), 'String', imaHeaderInfo);
