-28	-4	-16	Left Cerebrum	Limbic Lobe	Parahippocampal Gyrus	Gray Matter	Amygdala
26	2	-16	Right Cerebrum	Limbic Lobe	Parahippocampal Gyrus	White Matter	*
-12	28	0	Left Cerebrum	Sub-lobar	Extra-Nuclear	White Matter	Corpus Callosum
4	16	12	Right Cerebrum	Sub-lobar	Lateral Ventricle	Cerebro-Spinal Fluid	*
-13	11	8	Left Cerebrum	Sub-lobar	Caudate	Gray Matter	Caudate Body
-6	10	4	Left Cerebrum	Sub-lobar	Caudate	Gray Matter	Caudate Head
34	-26	-4	Right Cerebrum	Sub-lobar	Caudate	Gray Matter	Caudate Tail
-40	-11	3	Left Cerebrum	Sub-lobar	Insula	White Matter	*
28	10	0	Right Cerebrum	Sub-lobar	Extra-Nuclear	White Matter	*
-28	10	4	Left Cerebrum	Sub-lobar	Extra-Nuclear	White Matter	*
36	0	-12	Right Cerebrum	Temporal Lobe	Superior Temporal Gyrus	White Matter	*
35	15	18	Right Cerebrum	Frontal Lobe	Sub-Gyral	White Matter	*
-38	16	8	Left Cerebrum	Sub-lobar	Insula	Gray Matter	Brodmann area 13
42	6	0	Right Cerebrum	Sub-lobar	Insula	Gray Matter	*
-45	-11	3	Left Cerebrum	Sub-lobar	Insula	*	*
38	20	5	Right Cerebrum	Sub-lobar	Insula	Gray Matter	Brodmann area 13
42	0	0	Right Cerebrum	Sub-lobar	Insula	Gray Matter	Brodmann area 13
38	4	8	Right Cerebrum	Sub-lobar	Insula	White Matter	*
-34	7	-12	Left Cerebrum	Temporal Lobe	Inferior Frontal Gyrus	Gray Matter	Brodmann area 13
9	-90	0	Right Cerebrum	Occipital Lobe	Lingual Gyrus	White Matter	*
10	-96	-6	Right Cerebrum	Occipital Lobe	Lingual Gyrus	White Matter	*
1	-85	7	Inter-Hemispheric	*	*	*	*
4	-71	17	Right Cerebrum	Occipital Lobe	Cuneus	Gray Matter	Brodmann area 18
-30	-84	0	Left Cerebrum	Occipital Lobe	Middle Occipital Gyrus	Gray Matter	Brodmann area 18
4	-76	11	Right Cerebrum	Occipital Lobe	Cuneus	Gray Matter	Brodmann area 17
-4	-80	8	Left Cerebrum	Occipital Lobe	Cuneus	Gray Matter	Brodmann area 17
